'use strict'

module.exports = function Image(data){
  // console.log('buffer: ', data)
  this.buffer =  Buffer.from(data)
   // console.log('type: ', data.slice(0, 2).toString())
  this.header = this.buffer.toString('utf8',0,2)
 // console.log('size in bytes: ', data.readUInt32LE(2))
 this.bytes = this.buffer.readUInt32LE(2)
 // console.log('pixel array offset: ', data.readUInt32LE(10))
 this.arrayOffset = this.buffer.readUint32LE(10)
 // console.log('size of header: ', data.readUInt32LE(14))
 this.sizeOfHeader = this.buffer.readUInt32LE(14)
 // console.log('width in pixels: ', data.readUInt32LE(18))
 this.pixelWidth = this.buffer.readUInt32LE(18)
 // console.log('height in pixels: ', data.readUInt32LE(22))
 this.pixelHeight = this.buffer.readUInt32LE(22)
 // console.log('color planes: ', data.readUInt16LE(26))
 this.colorPlanes = this.buffer.readUInt32LE(26)
 // console.log('bits per pixel: ', data.readUInt16LE(28))
 this.bitsPerPixel = this.buffer.readUInt32LE(28)
 // console.log('compression method: ', data.readUInt16LE(30))
 this.compressionMethod = this.buffer.readUInt32LE(30)
 // console.log('image size: ', data.readUInt32LE(34))
 this.imageSize = this.buffer.readUInt32LE(34)
 // console.log('horizontal resolution: ', data.readUInt32LE(38))
 this.horizontalRes = this.buffer.readUInt32LE(38)
 // console.log('vertical resolution: ', data.readUInt32LE(42))
 this.verticalRes = this.buffer.readUInt32LE(42)
 // console.log('number of colors in the color palette: ', data.readUInt32LE(46))
 this.colorPalette = this.buffer.readUInt32LE(46)
 // console.log('number of important colors used: ', data.readUInt32LE(50))
 this.importantColors = this.buffer.readUInt32LE(50)
}
